version: '2'
services:
    server:
        build: server
        ports:
        - "53/udp:53/udp"
        links: 
        - mongo
        volumes:
        - /logs:/logs   
    mongo:
        image: "mongo"
        volumes:
        - /docker/mongodb:/data/db